### ISSUE TITLE
Language context sensitive crawling

### ISSUE THREAD

**Issue by bravegag** [gaocegege/scrala#16]
Language context sensitive crawling. I have a webapp which i would like to crawl and to index using e.g. Lucene but in this use-case I would prefer to do two crawlings or to segregate the crawling by language in some way. 

how do you cover this use-case or otherwise how would you incorporate it? Basically the language will be on the top of the response page e.g. 

```
<!DOCTYPE html>
<html lang="es">
...
</html>
```

**Comment by gaocegege** [comment]
Not sure if I got you. Do you mean you will have different spider logic for different languages?

**Comment by bravegag** [comment]
@gaocegege Thank you! I'll use scrala to crawl my web application, and then will use Lucene to index the pages but I have my indexes segregated by language e.g. when you search the English version of the website only english results will appear whereas when you look in say e.g. Spanish only Spanish results will appear.

I just realized I can cover this use-case as follows:
- Start the crawling for every different language e.g. `http://localhost:9000/lang/es`
- then use the `Filter` provision/feature to filter out any language switch link.

That's it, it will work.

btw expect some additional PR's
