### ISSUE TITLE
Other java/scala crawlers 

### ISSUE THREAD

**Issue by at15** [gaocegege/scrala#4]
There are already some java/scala crawlers on github, what's the difference between `scrala` and those projects?

I picked some of them

(order by star desc)
- https://github.com/code4craft/webmagic
- https://github.com/yasserg/crawler4j
- **https://github.com/fhopf/akka-crawler-example this one also use akka**

**Comment by gaocegege** [comment]
compared with webmagic and crawler4j, it written by scala.

compared with akka-crawler-example, it supports multithread and can easily become distributed.

**Comment by gaocegege** [comment]
In a word, 只是手痒想造轮子了而已

**Comment by at15** [comment]
@gaocegege 手痒玩游戏额

**Comment by gaocegege** [comment]
懒得出门。。。。

**Comment by hczhcz** [comment]
于是测女神真的玩游戏了……

**Comment by gaocegege** [comment]
Orz
