### ISSUE TITLE
有面临弃坑的危险 _(:зゝ∠)_

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/scrala#5]
沉迷游戏不能自拔

**Comment by at15** [comment]
.... 话说我又发现了个叫 apache nutch 的爬虫....看上去屌的不行 http://nutch.apache.org/ btw:少年来玩tf2么? 

related to #4

**Comment by gaocegege** [comment]
@at15 这个非常有名啊，不过他更加适合做水平爬虫，就是搜索引擎爬虫。。

**Comment by gaocegege** [comment]
我尽力填坑！应该是过年的时候才有时间填了！

**Comment by at15** [comment]
@gaocegege 然后过年就玩游戏去了....

**Comment by gaocegege** [comment]
@at15 不说出来还能做朋友

**Comment by hczhcz** [comment]
说出来了只能在一起了

**Comment by gaocegege** [comment]
@hczhcz 不说出来还能做朋友。。。

**Comment by mrmiywj** [comment]
说出来了只能在一起了
