### ISSUE TITLE
The halting problem

### ISSUE THREAD

**Issue by gaocegege** [gaocegege/scrala#6]
对于爬虫不知道自己什么时候停止的问题，产生的原因是因为现在过于简单粗暴的调度。之后可能需要更加保证时序的调度方法来实现。

现在的做法是每次请求来了，无论多少个先都给downloaderManager来处理，而downloaderManager又不知道自己会不会继续收到来自Engine的请求，所以整个系统没一个东西知道啥时候程序需要停止。

之后希望改下，由downloaderManager来主动push请求，每次只获得一个。感觉这样可以解决这个问题。还需要再思考下。。

**Comment by at15** [comment]
思考的结果就是去玩游戏了....

**Comment by gaocegege** [comment]
@at15 不说出来真的还能做朋友

**Comment by gaocegege** [comment]
```
    // One downloader situation: 
    // pop the element, so in this message, the scheduler is empty,
    // and dowloaderManager dispatch the work, when it's done,
    // THE BAD THING happened, everytime the downloader has done, 
    // it will send end message to engine, and the scheduler is always
    // empty, then will call stop multi times.
    // FXXK THE ASYNCHRONOUS!!!!!!!!!!!
```

思路：毒丸

**Comment by at15** [comment]
@gaocegege 0.0 所以是要提前开始过年了?

**Comment by gaocegege** [comment]
...@at15
明天考试，后天答辩，马上开题了，开始作死了

**Comment by gaocegege** [comment]
poison不能满足需求，考虑使用一个计数器，结合worker的状态共同决定程序什么时候结束

**Comment by gaocegege** [comment]
fixed

**Comment by at15** [comment]
@gaocegege mention the commit in the issue or mention the issue in the commit?

**Comment by gaocegege** [comment]
b8049122c37f31cbeee0c1ea87c1966b681abeaa
